language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_PAGES_DEPLOY: true
  - PATH: node_modules/.bin/:$PATH
  - REPO_SLUG: idle-dog/sexy-blocks
  - secure: Trx80crDQU+R7SE9AeLXxiYN/tJ3ys7g2CR82VdimUoXoEpzH4tEvR2j3ldN7IvFJ43XD6/+TVzA8xK89mv3rYRdXV28ajWQlme+pPxBw0Kc4sgiXM3Go0va4rokrQxFSOqFXeKQYsL650qdwt9Z8VJz0W0AuMlU+YOGNRZmppDte4J1OiNQxDF8FpJnf1MfSP3YyLXXlWR4Aosv4eWdYy3Pyg4UmQ9mF0u24zlEsA+mCZy36NuDkPxqsbbASg9QJlYuGYBrHmBjIxKCrKsfHWGcHWFYcxW7fRPGc3JjS2/MeRXIdhtiGUgqaY5YtfaQ8Gbxsvliq5NdneHkDf2uEtMSoGbRSW49fGWLDHMUBwv+T3+zPrE7q277OL4p0RlbaB2HPuhDJLmYU6Xp5QsjKT0qU6wqOT2xNyeXW5AX0moCP8m9Mg3Q2YIxoL7HFVHKrHIVHJ1zMt8MdsnS9x4CZULwPRoQxZkr0DBmHk8wrBUahknMJ2oAUjWP31ov5HpKFFPMeWSk1WU+JHHLjm2bdJqrUuvuNpTpIAUP0p8HAFyX1IT2nIYq81M8Qd+m23fv7trRaekdbkSCU8GoPuUDXZrMqUUrEqz9kqtryBezdx4tjTPfFVfpkTED2SWLB30ri1mixUn7UW/kyXEadvVJeOkQ0QRi9cof8YqgEHtyMyI=
install:
- npm install fis@1.9.34
- fis -v
script: sh .deploy.sh
cache:
  directories:
  - node_modules
branches:
  only:
  - master
